### 시연 Collection
### Base URL 설정
@productUrl = http://localhost:8080
@purchaseUrl = http://localhost:8081
@stockUrl = http://localhost:8082
@searchUrl = http://localhost:8083

### 시나리오1. 상품 등록 -> 재고 모듈 재고 등록 / 검색 모듈 색인
### 1. 상품 생성 (Product Create)
POST {{productUrl}}/api/v1/product
Content-Type: application/json

{
  "sellerId": "SELLER_FASHION_001",
  "categoryId": "CATEGORY_CLOTHING_001",
  "name": "코튼 티셔츠",
  "brand": "베이직웨어",
  "description": "100% 면 소재의 편안한 착용감을 제공하는 베이직 티셔츠입니다.",
  "priceAmount": 29000,
  "priceCurrency": "KRW",
  "variants": [
    {
      "optionCombination": "{\"color\":\"white\",\"size\":\"S\"}",
      "price": 29000,
      "currency": "KRW",
      "stockQuantity": 100
    },
    {
      "optionCombination": "{\"color\":\"white\",\"size\":\"M\"}",
      "price": 29000,
      "currency": "KRW",
      "stockQuantity": 150
    },
    {
      "optionCombination": "{\"color\":\"white\",\"size\":\"L\"}",
      "price": 29000,
      "currency": "KRW",
      "stockQuantity": 120
    },
    {
      "optionCombination": "{\"color\":\"black\",\"size\":\"S\"}",
      "price": 29000,
      "currency": "KRW",
      "stockQuantity": 80
    },
    {
      "optionCombination": "{\"color\":\"black\",\"size\":\"M\"}",
      "price": 29000,
      "currency": "KRW",
      "stockQuantity": 200
    },
    {
      "optionCombination": "{\"color\":\"black\",\"size\":\"L\"}",
      "price": 29000,
      "currency": "KRW",
      "stockQuantity": 180
    }
  ]
}

> {%
    // 응답에서 productId 추출
    client.global.set("productId", response.body.productId);
    client.global.set("sellerId", response.body.sellerId);
    client.global.set("name", response.body.name)
%}


### 2. 상품 정보 수정
PATCH http://localhost:8080/api/v1/product/{{productId}}
Content-Type: application/json

{
  "sellerId": "{{sellerId}}",
  "brand": "변경된 브랜드"
}

### 상품 삭제 사전 작업
PATCH http://localhost:8080/api/v1/product/{{productId}}/inactivate
X-Seller-Id: {{sellerId}}

### 3. 상품 삭제
DELETE http://localhost:8080/api/v1/product/{{productId}}
X-Seller-Id: {{sellerId}}

### 4. 키워드 검색
### 검색 & 정렬 & 필터링
// name에 키워드 입력

GET {{searchUrl}}/api/v1/product/search_2?keyword={{name}}&sortField=basePrice&sortOrder=asc&page=0&size=10

### 5. 장바구니 담기
### 6. 장바구니 상품 주문

### 7. 주문 상태 확인
### 8. 구매 확정
### 9. 리뷰 작성
### 10. 다른 사용자의 리뷰 조회