spring:
  application:
    name: commerce-search-service
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:search
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: elastictest
    ssl:
      certificate-validation-mode: none
  jackson:
    serialization:
      write-dates-as-timestamps: false
    modules:
      jsr310: true



