name: Commerce-2 Ci/Cd Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

# AWS 설정 정보
env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: public.ecr.aws/f5h1p0v2
  ECS_CLUSTER:

# 3단계 이미지 Push 및 배포
push-to-ecr:
  runs_on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Docker image
      run: |
        chmod +x ./gradlew
        ./gradlew :service:stock:build :service:stock:test
        
        # Docker 이미지 빌드
        docker build -t $ECR_REGISTRY/service/stock:latest -f service/stock/Dockerfile .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Push to ECR
      run: |
        docker push $ECR_REGISTRY/service/stock:latest 
